# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
isecl_repo: "https://github.com/intel-secl/build-manifest.git"
isecl_repo_tag: "refs/tags/v4.1.1"
isecl_repo_manifest: "manifest/data-sovereignty.xml"

isecl_build_dir: "{{ project_dir }}/intel-secl"
isecl_helm_charts_dir: "{{ project_dir }}/helm-charts/isecl"
isecl_env_file: "{{ project_dir }}/helm-charts/isecl/isecl-k8s.env"

isecl_nfs_client_mount_path: "/mnt/nfs_client_share"
isecl_nfs_server_dir: "/mnt/nfs_share"
