# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

_cert_server_name: telegraf
_cert_secret_name: telegraf-tls

_observability_telegraf_version: v1.0
_observability_telegraf_git_url: https://github.com/intel/observability-telegraf.git

_image_name: intel/observability-telegraf
_image_tag: "1.0"
_image_repo_path: "{{ _registry_ip_address }}:{{ _registry_port }}/{{ _image_name }}"

telemetry_telegraf_port: 9105
_telegraf_tag: 1.21.3-alpine
