# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: check if single node deployment
  set_fact:
    singlenode: "{{ groups['edgenode_group'] | length == 1
      and hostvars[groups['controller_group'][0]]['ansible_nodename'] == hostvars[groups['edgenode_group'][0]]['ansible_nodename'] }}"
  tags: always
- name: print single node info
  debug:
    msg: Cluster detected as single node deployment
  when: singlenode
  tags: always

- block:
  - name: kubernetes/install
    include_tasks: ../roles/kubernetes/install/tasks/readiness.yml
  - name: kubernetes/controlplane
    include_tasks: ../roles/kubernetes/controlplane/tasks/readiness.yml
    when: "'controller_group' in group_names"
  - name: kubernetes/node
    include_tasks: ../roles/kubernetes/node/tasks/readiness.yml
    when: "'edgenode_group' in group_names"
  tags: kubernetes  # when tags are applied to the block, the apply is not needed

- block:
  - name: harbor_registry/controlplane
    include_tasks: ../roles/kubernetes/harbor_registry/controlplane/tasks/readiness.yml
    when: "'controller_group' in group_names"
  tags: harbor

- block:
  - name: calico
    include_tasks: ../roles/kubernetes/cni/calico/controlplane/tasks/readiness.yml
    when:
      - "'controller_group' in group_names"
      - "'calico' in kubernetes_cnis"
  tags: cni, calico

- block:
  - name: multus/controlplane
    include_tasks: ../roles/kubernetes/cni/multus/controlplane/tasks/readiness.yml
    when:
      - "'controller_group' in group_names"
      - "kubernetes_cnis|length > 1"
  - name: multus/node
    include_tasks: ../roles/kubernetes/cni/multus/node/tasks/readiness.yml
    when:
      - "'edgenode_group' in group_names"
      - "kubernetes_cnis|length > 1"
  tags: cni, multus

- block:
  - name: nfd
    include_tasks: ../roles/kubernetes/nfd/tasks/readiness.yml
  tags: nfd
  when:
    - "'controller_group' in group_names"
    - ne_nfd_enable | default(True)

- block:
  - name: cadvisor controlplane
    include_tasks: ../roles/telemetry/cadvisor/tasks/readiness.yml
    when:
      - "'controller_group' in group_names"
      - telemetry_cadvisor_enable | default(True)
  - name: collectd controlplane
    include_tasks: ../roles/telemetry/collectd/controlplane/tasks/readiness.yml
    when:
      - "'controller_group' in group_names"
      - telemetry_collectd_enable | default(True)
  - name: prometheus
    include_tasks: ../roles/telemetry/prometheus/tasks/readiness.yml
    when:
      - "'controller_group' in group_names"
      - telemetry_prometheus_enable | default(True)
      
  tags: telemetry
